# Generated by Django 5.1.1 on 2024-10-18 07:46

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contactno', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='NP')),
                ('address', models.TextField()),
            ],
        ),
    ]
